### ISSUE TITLE
Spamis.fun crack

### ISSUE THREAD

**Issue by RedyRT** [DortDev/Spamis.fun-crack#1]
thanks very much for this crack, but... 
what is the password and username?
![изображение](https://user-images.githubusercontent.com/64935439/88441533-0c5b4100-ce1a-11ea-88db-dbb8a43ecaf6.png)

**Comment by DortDev** [comment]
Just put anything. Have a good one!

**Comment by RedyRT** [comment]
> 
> 
> Just put anything. Have a good one!



> 
> 
> Just put anything. Have a good one!

I put password anything, but it says login failed no matter how hard I try

**Comment by DortDev** [comment]
I'll look into it
